Repository pysal/spaghetti, pull requests merged in 2019-05, with the labels that each got.

#261 [WIP] adding support for python3.7
  .travis.yml
Labels: enhancement, package maintenance

#263 updating supported python versions in setup.py
  setup.py
Labels: package maintenance

#259 Switch snapping to Rtree package?
  requirements.txt
  spaghetti/util.py
Labels: bug, enhancement, help wanted

#267 updating requirements in README
  README.md
Labels: package maintenance

#271 updating README.md
  README.md
Labels: package maintenance

#269 3.5 --> 3.7 readthedocs
  doc/_static/pysal-styles.css
  readthedocs.yml
Labels: bug

#272 fix docs building
  .travis.yml
  environment.yml
  readthedocs.yml
  requirements_docs.txt
Labels: bug, enhancement, package maintenance

#273 Update docsite
  doc/index.rst
  doc/installation.rst
Labels: enhancement, package maintenance, priority-high

#274 updating README
  README.md
Labels: enhancement, package maintenance

#275 Updating notebooks prior to v1.3 release
  doc/index.rst
  notebooks/Facility_Location.ipynb
  notebooks/Network_Usage.ipynb
  notebooks/Snapping_Demonstration.ipynb
  notebooks/Spaghetti_Pointpatterns_Empirical.ipynb
Labels: package maintenance

#276 v1.2 --> 1.3rc1 (for release candidate)
  CHANGELOG.md
  spaghetti/__init__.py
  tools/changelog_1.3rc1.md
  tools/gitcount.ipynb
Labels: enhancement, package maintenance, priority-high

#278 version bump to include req_dev in MANIFEST.in
  MANIFEST.in
  spaghetti/__init__.py
Labels: bug, priority-high

#279 Update changelog
  CHANGELOG.md
  tools/changelog_1.3rc2.md
  tools/gitcount.ipynb
Labels: bug

#280 Bump version 1.3rc2 --> 1.3
  CHANGELOG.md
  spaghetti/__init__.py
  tools/changelog_1.3.md
  tools/gitcount.ipynb
Labels: package maintenance, priority-high, version

#282 update Changelog
  CHANGELOG.md
Labels: package maintenance, version

#283 remove extra line in .travis.yml
  .travis.yml
Labels: package maintenance
