Repository pysal/spaghetti, pull requests merged in 2020-06, with the labels that each got.

#495 [DOC] remove additional lines in doc-strings Parameters, Returns
  spaghetti/analysis.py
  spaghetti/network.py
  spaghetti/util.py
Labels: docs

#499 create dependabot.yml
  .github/dependabot.yml
Labels: GitHub actions, testing

#504 check requirements in dependabot
  .github/dependabot.yml
Labels: dependencies, package maintenance, requirements
