Repository pysal/spaghetti, pull requests merged in 2021-06, with the labels that each got.

#624 trim down Statement of Need section
  paper/paper.md
Labels: JOSS

#626 Minor formatting fixes
  paper/paper.md
Labels: JOSS

#629 Drop support for Python 3.6
  .github/workflows/unittests.yml
  ci/36.yaml
  setup.py
Labels: python

#630 split arc by count functionality
  notebooks/network-segmentation.ipynb
  spaghetti/network.py
  spaghetti/tests/network_unittest_classes.py
  spaghetti/util.py
Labels: enhancement

#633 removing descartes requirement
  environment.yml
  requirements_notebooks_conda.txt
Labels: dependencies, requirements

#634 Try new release action (softprops/action-gh-release)
  .github/workflows/release_and_publish.yml
  spaghetti/__init__.py
Labels: github_actions, release
